---
- name: Git - Ensure prerequisites packages are installed.
  apt:
    package: "{{ redmine_git_packages }}"
    state: present

- name: Git - Is this your first time?
  stat:
    path: "{{ redmine_install_dir }}/.git"
  register: redmine_first_pass

- name: Git - Clone bare repository.
  git:
    bare: yes
    repo: "{{ redmine_git_repo }}"
    dest: "{{ redmine_install_dir }}/.git"
    version: "{{ redmine_git_version }}"
    force: yes
    accept_hostkey: yes
  register: redmine_git_result
  changed_when: "redmine_git_result.after|default('after') != redmine_git_result.before|default('before')"
  when: redmine_first_pass.stat.exists == false
  become_user: "{{ redmine_user }}"

- name: Git - Convert bare repository.
  lineinfile:
    path: "{{ redmine_install_dir }}/.git/config"
    regexp: "bare = true"
    line: "bare = false"

- name: Git - Clone repository.
  git:
    repo: "{{ redmine_git_repo }}"
    dest: "{{ redmine_install_dir }}"
    version: "{{ redmine_git_version }}"
    force: yes
    accept_hostkey: yes
  register: redmine_git_result
  changed_when: "redmine_git_result.after|default('after') != redmine_git_result.before|default('before')"
  become_user: "{{ redmine_user }}"

- name: Git - Ensure database.yml is set.
  template:
    src: database.yml.j2
    dest: "{{ redmine_install_dir }}/config/database.yml"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"

- name: Ensure redmine ownership.
  file:
    path: "{{ redmine_install_dir }}"
    owner: "{{ redmine_user }}"
    group: "{{ redmine_group }}"
    recurse: yes

- include_tasks: 'bundle.yml'
